// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkKngiVMtfnivo9qAgwHpHSRcWCEWSHKQ',
    appId: '1:823326984545:web:3a804bfb3ba647b8e6dd20',
    messagingSenderId: '823326984545',
    projectId: 'library-management-syste-52668',
    authDomain: 'library-management-syste-52668.firebaseapp.com',
    storageBucket: 'library-management-syste-52668.appspot.com',
    measurementId: 'G-N3EGLC34P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrpusGHsDI6L3booDFo3kQC_KcYbtjoJU',
    appId: '1:823326984545:android:b8d3cb328e888f4ce6dd20',
    messagingSenderId: '823326984545',
    projectId: 'library-management-syste-52668',
    storageBucket: 'library-management-syste-52668.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1tDlIVH7i-iLEeJLHoN2_EobmffutFLI',
    appId: '1:823326984545:ios:81d2466f20a45402e6dd20',
    messagingSenderId: '823326984545',
    projectId: 'library-management-syste-52668',
    storageBucket: 'library-management-syste-52668.appspot.com',
    iosBundleId: 'com.lexusdevelopers.libraryManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1tDlIVH7i-iLEeJLHoN2_EobmffutFLI',
    appId: '1:823326984545:ios:81d2466f20a45402e6dd20',
    messagingSenderId: '823326984545',
    projectId: 'library-management-syste-52668',
    storageBucket: 'library-management-syste-52668.appspot.com',
    iosBundleId: 'com.lexusdevelopers.libraryManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkKngiVMtfnivo9qAgwHpHSRcWCEWSHKQ',
    appId: '1:823326984545:web:8359607e8d3617b7e6dd20',
    messagingSenderId: '823326984545',
    projectId: 'library-management-syste-52668',
    authDomain: 'library-management-syste-52668.firebaseapp.com',
    storageBucket: 'library-management-syste-52668.appspot.com',
    measurementId: 'G-7606JV5X48',
  );
}
